# Generated by Django 5.1.3 on 2026-01-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.IntegerField(),
        ),
    ]
